package advancedlevel;
// Generated Mar 5, 2014 6:51:52 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ExamTry generated by hbm2java
 */
public class ExamTry  implements java.io.Serializable {


     private String index;
     private Date year;
     private int attemptNumber;
     private Double overallZ;
     private Integer islandRank;
     private Integer districtRank;
     private String nicNumber;
     private String districtId;
     private String examCenterId;
     private String fieldName;

    public ExamTry() {
    }

	
    public ExamTry(String index, Date year, int attemptNumber, String nicNumber, String districtId, String examCenterId, String fieldName) {
        this.index = index;
        this.year = year;
        this.attemptNumber = attemptNumber;
        this.nicNumber = nicNumber;
        this.districtId = districtId;
        this.examCenterId = examCenterId;
        this.fieldName = fieldName;
    }
    public ExamTry(String index, Date year, int attemptNumber, Double overallZ, Integer islandRank, Integer districtRank, String nicNumber, String districtId, String examCenterId, String fieldName) {
       this.index = index;
       this.year = year;
       this.attemptNumber = attemptNumber;
       this.overallZ = overallZ;
       this.islandRank = islandRank;
       this.districtRank = districtRank;
       this.nicNumber = nicNumber;
       this.districtId = districtId;
       this.examCenterId = examCenterId;
       this.fieldName = fieldName;
    }
   
    public String getIndex() {
        return this.index;
    }
    
    public void setIndex(String index) {
        this.index = index;
    }
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }
    public int getAttemptNumber() {
        return this.attemptNumber;
    }
    
    public void setAttemptNumber(int attemptNumber) {
        this.attemptNumber = attemptNumber;
    }
    public Double getOverallZ() {
        return this.overallZ;
    }
    
    public void setOverallZ(Double overallZ) {
        this.overallZ = overallZ;
    }
    public Integer getIslandRank() {
        return this.islandRank;
    }
    
    public void setIslandRank(Integer islandRank) {
        this.islandRank = islandRank;
    }
    public Integer getDistrictRank() {
        return this.districtRank;
    }
    
    public void setDistrictRank(Integer districtRank) {
        this.districtRank = districtRank;
    }
    public String getNicNumber() {
        return this.nicNumber;
    }
    
    public void setNicNumber(String nicNumber) {
        this.nicNumber = nicNumber;
    }
    public String getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(String districtId) {
        this.districtId = districtId;
    }
    public String getExamCenterId() {
        return this.examCenterId;
    }
    
    public void setExamCenterId(String examCenterId) {
        this.examCenterId = examCenterId;
    }
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }




}


