package advancedlevel;
// Generated Mar 6, 2014 11:09:07 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ExamTry generated by hbm2java
 */
public class ExamTry  implements java.io.Serializable {


     private String indexNum;
     private String nicNumber;
     private Date regYear;
     private int attemptNumber;
     private Double overallZ;
     private Integer islandRank;
     private Integer districtRank;
     private String districtId;
     private String examCenterId;
     private String fieldName;

    public ExamTry() {
    }

	
    public ExamTry(String indexNum, String nic, Date regYear, int attemptNumber, String districtId, String examCenterId, String fieldName) {
        this.indexNum = indexNum;
        this.nicNumber = nic;
        this.regYear = regYear;
        this.attemptNumber = attemptNumber;
        this.districtId = districtId;
        this.examCenterId = examCenterId;
        this.fieldName = fieldName;
    }
    public ExamTry(String indexNum, String nic, Date regYear, int attemptNumber, Double overallZ, Integer islandRank, Integer districtRank, String districtId, String examCenterId, String fieldName) {
       this.indexNum = indexNum;
       this.nicNumber = nic;
       this.regYear = regYear;
       this.attemptNumber = attemptNumber;
       this.overallZ = overallZ;
       this.islandRank = islandRank;
       this.districtRank = districtRank;
       this.districtId = districtId;
       this.examCenterId = examCenterId;
       this.fieldName = fieldName;
    }
   
    public String getIndexNum() {
        return this.indexNum;
    }
    
    public void setIndexNum(String indexNum) {
        this.indexNum = indexNum;
    }
    public String getNicNumber() {
        return this.nicNumber;
    }
    
    public void setNicNumber(String nicNumber) {
        this.nicNumber = nicNumber;
    }
    public Date getRegYear() {
        return this.regYear;
    }
    
    public void setRegYear(Date regYear) {
        this.regYear = regYear;
    }
    public int getAttemptNumber() {
        return this.attemptNumber;
    }
    
    public void setAttemptNumber(int attemptNumber) {
        this.attemptNumber = attemptNumber;
    }
    public Double getOverallZ() {
        return this.overallZ;
    }
    
    public void setOverallZ(Double overallZ) {
        this.overallZ = overallZ;
    }
    public Integer getIslandRank() {
        return this.islandRank;
    }
    
    public void setIslandRank(Integer islandRank) {
        this.islandRank = islandRank;
    }
    public Integer getDistrictRank() {
        return this.districtRank;
    }
    
    public void setDistrictRank(Integer districtRank) {
        this.districtRank = districtRank;
    }
    public String getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(String districtId) {
        this.districtId = districtId;
    }
    public String getExamCenterId() {
        return this.examCenterId;
    }
    
    public void setExamCenterId(String examCenterId) {
        this.examCenterId = examCenterId;
    }
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }




}


