package advancedlevel;
// Generated Mar 4, 2014 8:54:47 PM by Hibernate Tools 3.2.1.GA



/**
 * School generated by hbm2java
 */
public class School  implements java.io.Serializable {


     private String schoolId;
     private String schoolName;
     private String schoolAddress;

    public School() {
    }

    public School(String schoolId, String schoolName, String schoolAddress) {
       this.schoolId = schoolId;
       this.schoolName = schoolName;
       this.schoolAddress = schoolAddress;
    }
   
    public String getSchoolId() {
        return this.schoolId;
    }
    
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }
    public String getSchoolName() {
        return this.schoolName;
    }
    
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }
    public String getSchoolAddress() {
        return this.schoolAddress;
    }
    
    public void setSchoolAddress(String schoolAddress) {
        this.schoolAddress = schoolAddress;
    }




}


