package advancedlevel;
// Generated Mar 5, 2014 2:11:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String nicNumber;
     private String studentName;
     private String studentAddress;
     private Date birthday;
     private byte[] private_;
     private String schoolId;

    public Student() {
    }

    public Student(String nicNumber, String studentName, String studentAddress, Date birthday, byte[] private_, String schoolId) {
       this.nicNumber = nicNumber;
       this.studentName = studentName;
       this.studentAddress = studentAddress;
       this.birthday = birthday;
       this.private_ = private_;
       this.schoolId = schoolId;
    }
   
    public String getNicNumber() {
        return this.nicNumber;
    }
    
    public void setNicNumber(String nicNumber) {
        this.nicNumber = nicNumber;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getStudentAddress() {
        return this.studentAddress;
    }
    
    public void setStudentAddress(String studentAddress) {
        this.studentAddress = studentAddress;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public byte[] getPrivate_() {
        return this.private_;
    }
    
    public void setPrivate_(byte[] private_) {
        this.private_ = private_;
    }
    public String getSchoolId() {
        return this.schoolId;
    }
    
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }




}


