package advancedlevel;
// Generated Mar 4, 2014 11:28:55 PM by Hibernate Tools 3.2.1.GA



/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private String subjectId;
     private String subjectName;
     private byte[] main;
     private String fieldName;

    public Subject() {
    }

    public Subject(String subjectId, String subjectName, byte[] main, String fieldName) {
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.main = main;
       this.fieldName = fieldName;
    }
   
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public byte[] getMain() {
        return this.main;
    }
    
    public void setMain(byte[] main) {
        this.main = main;
    }
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }




}


