package advancedlevel;
// Generated Mar 6, 2014 4:19:40 PM by Hibernate Tools 3.2.1.GA



/**
 * Takes generated by hbm2java
 */
public class Takes  implements java.io.Serializable {


     private TakesId id;
     private Double marks;
     private String grade;
     private byte[] presence;
     private byte[] suspended;
     private Double ZScore;

    public Takes() {
    }

	
    public Takes(TakesId id) {
        this.id = id;
    }
    public Takes(TakesId id, Double marks, String grade, byte[] presence, byte[] suspended, Double ZScore) {
       this.id = id;
       this.marks = marks;
       this.grade = grade;
       this.presence = presence;
       this.suspended = suspended;
       this.ZScore = ZScore;
    }
   
    public TakesId getId() {
        return this.id;
    }
    
    public void setId(TakesId id) {
        this.id = id;
    }
    public Double getMarks() {
        return this.marks;
    }
    
    public void setMarks(Double marks) {
        this.marks = marks;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public byte[] getPresence() {
        return this.presence;
    }
    
    public void setPresence(byte[] presence) {
        this.presence = presence;
    }
    public byte[] getSuspended() {
        return this.suspended;
    }
    
    public void setSuspended(byte[] suspended) {
        this.suspended = suspended;
    }
    public Double getZScore() {
        return this.ZScore;
    }
    
    public void setZScore(Double ZScore) {
        this.ZScore = ZScore;
    }




}


