package advancedlevel;
// Generated Mar 7, 2014 9:11:12 AM by Hibernate Tools 3.2.1.GA



/**
 * TakesId generated by hbm2java
 */
public class TakesId  implements java.io.Serializable {


     private String subjectId;
     private String indexNum;

    public TakesId() {
    }

    public TakesId(String subjectId, String indexNum) {
       this.subjectId = subjectId;
       this.indexNum = indexNum;
    }
   
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getIndexNum() {
        return this.indexNum;
    }
    
    public void setIndexNum(String indexNum) {
        this.indexNum = indexNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TakesId) ) return false;
		 TakesId castOther = ( TakesId ) other; 
         
		 return ( (this.getSubjectId()==castOther.getSubjectId()) || ( this.getSubjectId()!=null && castOther.getSubjectId()!=null && this.getSubjectId().equals(castOther.getSubjectId()) ) )
 && ( (this.getIndexNum()==castOther.getIndexNum()) || ( this.getIndexNum()!=null && castOther.getIndexNum()!=null && this.getIndexNum().equals(castOther.getIndexNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSubjectId() == null ? 0 : this.getSubjectId().hashCode() );
         result = 37 * result + ( getIndexNum() == null ? 0 : this.getIndexNum().hashCode() );
         return result;
   }   


}


