package advancedlevel;
// Generated Mar 7, 2014 9:11:12 AM by Hibernate Tools 3.2.1.GA



/**
 * TakesId generated by hbm2java
 */
public class TakesId  implements java.io.Serializable {


     private String subjectId;
     private String indexNumber;

    public TakesId() {
    }

    public TakesId(String subjectId, String indexNumber) {
       this.subjectId = subjectId;
       this.indexNumber = indexNumber;
    }
   
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getIndexNumber() {
        return this.indexNumber;
    }
    
    public void setIndexNumber(String indexNumber) {
        this.indexNumber = indexNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TakesId) ) return false;
		 TakesId castOther = ( TakesId ) other; 
         
		 return ( (this.getSubjectId()==castOther.getSubjectId()) || ( this.getSubjectId()!=null && castOther.getSubjectId()!=null && this.getSubjectId().equals(castOther.getSubjectId()) ) )
 && ( (this.getIndexNumber()==castOther.getIndexNumber()) || ( this.getIndexNumber()!=null && castOther.getIndexNumber()!=null && this.getIndexNumber().equals(castOther.getIndexNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSubjectId() == null ? 0 : this.getSubjectId().hashCode() );
         result = 37 * result + ( getIndexNumber() == null ? 0 : this.getIndexNumber().hashCode() );
         return result;
   }   


}


